package io.jenkins.plugins.naverworks.exception;

public class RuntimeExceptionWrapper extends RuntimeException {

    public RuntimeExceptionWrapper(Throwable cause) {
        super(cause);
    }

}
